CREATE TABLE category (
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
categoryName VARCHAR(50) NOT NULL,
description VARCHAR(50),
PRIMARY KEY (id)
);

CREATE TABLE product (
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
productName VARCHAR(50) NOT NULL,
code VARCHAR(50) NOT NULL,
weight Double NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE inventory (
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
productid Integer NOT NULL,
quantity Integer NOT NULL,
location VARCHAR(50) NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (productid) REFERENCES product(id)
);
